# Generated by Django 2.1.7 on 2019-03-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190318_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '菜单'), (1, '功能')], max_length=2, verbose_name='类型'),
        ),
    ]
