# Generated by Django 2.1.7 on 2019-04-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190320_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='permission',
            new_name='menus',
        ),
        migrations.RemoveField(
            model_name='route',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='routes',
            field=models.ManyToManyField(db_table='role_to_route', to='user.Route', verbose_name='角色路由'),
        ),
    ]
