# Generated by Django 2.1.7 on 2019-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190403_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_id',
            new_name='current_id',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_id',
            new_name='current_id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '菜单'), (1, '功能')], verbose_name='类型'),
        ),
    ]
