# Generated by Django 2.1.7 on 2019-04-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190403_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parent_id',
            new_name='parentId',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='current_id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='菜单ID'),
        ),
    ]
