# Generated by Django 2.1.7 on 2019-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190404_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='parent_id',
            new_name='parentId',
        ),
        migrations.RemoveField(
            model_name='route',
            name='current_id',
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='路由ID'),
        ),
    ]
