# Generated by Django 2.1.7 on 2019-04-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190404_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parentId',
            field=models.IntegerField(verbose_name='父菜单ID'),
        ),
        migrations.AlterField(
            model_name='route',
            name='parentId',
            field=models.IntegerField(verbose_name='父路由ID'),
        ),
    ]
