# Generated by Django 2.1.7 on 2019-04-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190404_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(max_length=128, null=True, verbose_name='菜单路径'),
        ),
    ]
