# Generated by Django 2.1.7 on 2019-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20190404_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=18, unique=True, verbose_name='名字'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=18, unique=True, verbose_name='用户账号'),
        ),
    ]
