# Generated by Django 2.1.7 on 2019-04-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190404_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='permission',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='路由权限标识'),
        ),
    ]
