# Generated by Django 2.1.7 on 2019-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_route_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='component_path',
            new_name='componentPath',
        ),
        migrations.AlterField(
            model_name='route',
            name='permission',
            field=models.CharField(max_length=128, null=True, verbose_name='路由权限标识'),
        ),
    ]
