# Generated by Django 2.1.7 on 2019-04-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=11, null=True, verbose_name='手机'),
        ),
    ]
