# Generated by Django 2.1.7 on 2019-04-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='trueName',
        ),
    ]
