# Generated by Django 2.1.7 on 2019-04-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190409_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
