# Generated by Django 2.1.7 on 2019-04-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20190409_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.CharField(choices=[(0, '管理员'), (1, '普通用户')], max_length=1),
        ),
    ]
