# Generated by Django 2.1.7 on 2019-04-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20190410_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
    ]
