# Generated by Django 2.1.7 on 2019-04-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_user_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_time',
        ),
    ]
