# Generated by Django 2.1.7 on 2019-04-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_user_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(default='', max_length=128, verbose_name='菜单路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='permission',
            field=models.CharField(default='', max_length=128, verbose_name='菜单权限标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
