# Generated by Django 2.1.7 on 2019-04-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20190414_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='菜单路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='permission',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='菜单权限标识'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(null=True, verbose_name='排序'),
        ),
    ]
