# Generated by Django 2.1.7 on 2019-04-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20190414_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(max_length=128, null=True, verbose_name='菜单路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='permission',
            field=models.CharField(max_length=128, null=True, verbose_name='菜单权限标识'),
        ),
        migrations.AlterField(
            model_name='route',
            name='path',
            field=models.CharField(max_length=128, unique=True, verbose_name='路由路径'),
        ),
    ]
