# Generated by Django 2.1.7 on 2019-04-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20190414_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='path',
            field=models.CharField(max_length=128, null=True, verbose_name='路由路径'),
        ),
    ]
