# Generated by Django 2.1.7 on 2019-04-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20190414_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='routes',
        ),
    ]
